package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient data from output files generated by the simulator and stores
 * the parsed records in a DataStorage object.
 */
public class FileDataReader implements DataReader {
    private String directoryPath;

    /**
     * Creates a FileDataReader for a given directory.
     *
     * @param directoryPath the path of the directory containing simulator output files
     */
    public FileDataReader(String directoryPath) {
        this.directoryPath = directoryPath;
    }

    /**
     * It reads all files in the directory and it adds valid patient records to the storage.
     *
     * This is the expected format per line:
     * patientId,measurementValue,recordType,timestamp
     *
     * @param dataStorage the storage where parsed records are saved
     * @throws IOException if files cannot be read
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File directory = new File(directoryPath);

        if (!directory.exists() || !directory.isDirectory()) {
            throw new IOException("Invalid directory: " + directoryPath);
        }

        File[] files = directory.listFiles();

        if (files == null) {
            return;
        }

        for (File file : files) {
            if (file.isFile()) {
                readFile(file, dataStorage);
            }
        }
    }

    private void readFile(File file, DataStorage dataStorage) throws IOException {
        try (BufferedReader bufferedReader = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = bufferedReader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        String[] parts = line.split(",");

        if (parts.length != 4) {
            return;
        }

        try {
            int patientId = Integer.parseInt(parts[0].trim());
            double measurementValue = Double.parseDouble(parts[1].trim());
            String recordType = parts[2].trim();
            long timestamp = Long.parseLong(parts[3].trim());

            dataStorage.addPatientData(patientId, measurementValue, recordType, timestamp);
        } catch (NumberFormatException exception) {
            // Invalid lines arre ignored because the simulator output could contain not valid data.
        }
    }
}